language: python
python:
  - "3.12"

services:
  - docker

env:
  global:
    - SERVICE_UUID=
    - SERVICE_VERSION=
    - AOS_UPLOAD_SERVICE_URL=https://aoscloud.io:10000/api/v10/services/versions/
    - SP_CERTIFICATE=meta_folder/sp-client.pem
    - PRIVATE_KEY=meta_folder/private_key.pem

install:
  - pip install docker-compose
  - sudo apt-get install curl
  - mkdir package

script:
  - docker pull aoscloud/aos_signer:1.0.0
  - docker run -v $(pwd)/meta_folder:/data/meta/ -v $(pwd)/src/:/data/src/ -v $(pwd)/package:/data/package aoscloud/aos_signer:1.0.0
  - curl --request POST -k -v --cacert meta_folder/rootCA.crt.pem --cert $SP_CERTIFICATE --key $PRIVATE_KEY --form "service=$SERVICE_UUID" --form "version=$SERVICE_VERSION"  --form "file=@package/service.tar.gz" $AOS_UPLOAD_SERVICE_URL
